### ISSUE TITLE
Instance level

### ISSUE THREAD

**Issue by shanqiu24** [2gunsu/monocon-pytorch#12]
Hello, when reading the tag data, if I change the filter conditions of the instance level, does it mean that the distance of the model I trained focus is different, and will the level filtering hyperparameter affect the evaluation process?

**Comment by 2gunsu** [comment]
Hello.
I'm really sorry for not being able to reply because I've been so busy. 😭😭

The filtering condition you mentioned is 

```python
DEFAULT_FILTER_CONFIG = {
    'min_height': 25,
    'min_depth': 2,
    'max_depth': 65,
    'max_truncation': 0.5,
    'max_occlusion': 2}
```
Are you talking about this?
If this is correct, how are you going to change this value?

The rest of the issues will be answered sequentially as soon as time permits.

**Comment by shanqiu24** [comment]
> Yes, for example, I changed the max_depth to 120, because the objects in my dataset are far away, and the number of objects is much more than the number in each image in KITTI, but unlike the easy, moderate, and hard filtering standards provided by KITTI official, the dataset I want to do does not have a unified filtering standard. If I change these filter criteria, will it affect my evaluation results? I mean, for example, another person who does the same dataset as me but uses different filter criteria, does it make sense for me to compare his evaluation results?😄

**Comment by 2gunsu** [comment]
The filtering rules applied to this code were proposed in [**MonoDLE(CVPR, 2021)**](https://openaccess.thecvf.com/content/CVPR2021/papers/Ma_Delving_Into_Localization_Errors_for_Monocular_3D_Object_Detection_CVPR_2021_paper.pdf). 
In this paper, the maximum depth of an object is limited, which degrades the overall performance because there is a less visual signal for objects that are too far away.

I don't know how the custom dataset you're using is structured and how different it is from KITTI, but I don't think this rule will be heavily influenced by the domain (dataset). Therefore, I think that if you increase the maximum depth to 120 as you said, the performance will decrease slightly. However, since the objects in your dataset are farther away than the objects in the KITTI dataset, you need to check the object distribution by depth first and increase the value appropriately.

**Comment by 2gunsu** [comment]
Close issue due to inactivity.
Other issues will be answered sequentially.
Thank You 😄
