### ISSUE TITLE
question

### ISSUE THREAD

**Issue by shanqiu24** [2gunsu/monocon-pytorch#15]
Do you plan to add Kitti test set prediction scripts to this repository to generate test set prediction files?😊

**Comment by 2gunsu** [comment]
I apologize for the delay in responding. 

Nice to meet you after a long time! 
I'm trying to add the code that makes the prediction result for the test set first, but I can't check it because I don't have a GPU available at the moment. I'd appreciate it if you could wait a little bit. 🥹

We will close the issue now, but if you have any questions, you can open it again anytime. Thank you.
