### ISSUE TITLE
How to set the  input image size

### ISSUE THREAD

**Issue by ClaireMei** [2gunsu/monocon-pytorch#17]
May I ask where to set the input image size? I didn't see this section in the configuration file. Besides, I didn't see the use of the 'Resize3d' function in any part of the code.

**Comment by 2gunsu** [comment]
Hello. I'm sorry for the late reply. 
As you said, **'Resize3D'**, which can adjust the size of the image, is not currently used for default transform.

If you want to use Resize3D, please add it as the first element of ```default_train_transforms``` in ```dataset/monocon_dataset.py```.

**[Example]**
If you want to resize the image to (256, 768), set the first element of the transform list as ```Resize3D(target_hw=(256, 768))``` as shown below. Since the size of the image has changed, when performing a transform that requires a size parameter like ```RandomCrop3D```, you need to set this parameter smaller than the image size.
```python
default_train_transforms = [
    Resize3D(target_hw=(256, 768)),
    PhotometricDistortion(
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    RandomShift(prob=0.5, shift_range=(-32, 32), hide_kpts_in_shift_area=True),
    RandomHorizontalFlip(prob=0.5),
    RandomCrop3D(prob=0.5, crop_size=(256, 320), hide_kpts_in_crop_area=True),
    Normalize(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375]),
    Pad(size_divisor=32),
    ToTensor(),
]
```

Also, if you want to perform resizing during validation or testing, add ```Resize3D``` to ```default_test_transforms``` as shown below.
```python
default_test_transforms = [
    Resize3D(target_hw=(256, 768)),
    Normalize(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375]),
    Pad(size_divisor=32),
    ToTensor(),
]
```

Actually, I don't know how the performance will be if the resizing proceeds. 🤔
Have a nice day!

**Comment by 2gunsu** [comment]
Close issue due to inactivity. If you have another question, feel free to reopen it.
